@extends('admin.layout')
@section('content')
@php($fields=\App\AdminHub\ResourceSchema::fields($schema,$mode==='create'?'create':'update'))
<section class="rounded bg-white p-6 shadow"><p class="text-sm text-slate-500"><a class="hover:underline" href="{{ route('admin.product.resources.table', [$productKey,$resourceKey]) }}">{{ $schema['label'] ?? $resourceKey }}</a> / {{ $mode }}</p><h1 class="text-2xl font-bold">{{ ucfirst($mode) }} {{ $schema['label'] ?? \Illuminate\Support\Str::headline($resourceKey) }}</h1>
@if($errors->any())<div class="mt-4 rounded bg-red-50 p-4 text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ $mode === 'create' ? route('admin.product.resources.store', [$productKey,$resourceKey]) : route('admin.product.resources.update', [$productKey,$resourceKey,$id]) }}" class="mt-6 space-y-4">@csrf @if($mode==='edit')@method('PATCH')@endif
@foreach($fields as $field)@php($key=$field['key']) @php($value=old($key, data_get($item,$key)))<label class="block"><span class="text-sm font-medium">{{ $field['label'] }}</span>
@switch($field['type']) @case('textarea')<textarea name="{{ $key }}" class="mt-1 w-full rounded border p-2" rows="4">{{ $value }}</textarea>@break @case('boolean')<input type="hidden" name="{{ $key }}" value="0"><input type="checkbox" name="{{ $key }}" value="1" @checked($value) class="mt-2 rounded border">@break @case('select')<select name="{{ $key }}" class="mt-1 w-full rounded border p-2">@foreach(($field['options'] ?? []) as $ok=>$ov)<option value="{{ is_array($ov)?($ov['value']??$ok):$ok }}" @selected((string)$value===(string)(is_array($ov)?($ov['value']??$ok):$ok))>{{ is_array($ov)?($ov['label']??$ov['value']??$ok):$ov }}</option>@endforeach</select>@break @case('json')<textarea name="{{ $key }}" class="mt-1 w-full rounded border p-2 font-mono text-sm" rows="6">{{ is_array($value) ? json_encode($value, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES) : $value }}</textarea>@break @default<input name="{{ $key }}" type="{{ in_array($field['type'], ['email','number','date','url'], true) ? $field['type'] : ($field['type']==='datetime'?'datetime-local':'text') }}" value="{{ $value }}" class="mt-1 w-full rounded border p-2">@endswitch
@error($key)<span class="text-sm text-red-700">{{ $message }}</span>@enderror</label>@endforeach
<div class="flex gap-2"><button class="rounded bg-blue-600 px-4 py-2 text-white">Save</button><a class="rounded bg-slate-100 px-4 py-2" href="{{ route('admin.product.resources.table', [$productKey,$resourceKey]) }}">Cancel</a></div></form></section>
@endsection
