@extends('admin.layout')
@section('content')
<section class="rounded bg-white p-6 shadow"><div class="flex items-center justify-between"><div><p class="text-sm text-slate-500">{{ $product['name'] ?? $productKey }} / Resources</p><h1 class="text-2xl font-bold">Product Resources</h1></div></div>
@if(! $response->success)<div class="mt-6 rounded border border-red-200 bg-red-50 p-4 text-red-800">{{ $response->error['message'] ?? 'Unable to load resources.' }}</div>
@else
@php($resources = $response->data['resources'] ?? $response->data['items'] ?? $response->data)
@if(empty($resources))<div class="mt-6 rounded border border-slate-200 bg-slate-50 p-8 text-center text-slate-600">No admin resources are available for this product yet.</div>@else
<div class="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach($resources as $key=>$resource)@php($resource=is_array($resource)?$resource:['key'=>$resource]) @php($rkey=$resource['key'] ?? (is_string($key)?$key:null)) @if($rkey)<a class="rounded border border-slate-200 p-4 hover:border-blue-300 hover:bg-blue-50" href="{{ route('admin.product.resources.table', [$productKey, $rkey]) }}"><div class="flex justify-between gap-3"><h2 class="font-semibold">{{ $resource['label'] ?? \Illuminate\Support\Str::headline($rkey) }}</h2>@if($resource['danger_level'] ?? null)<span class="rounded bg-amber-100 px-2 py-1 text-xs text-amber-800">{{ $resource['danger_level'] }}</span>@endif</div><p class="mt-1 text-xs font-mono text-slate-500">{{ $rkey }}</p>@if($resource['description'] ?? null)<p class="mt-3 text-sm text-slate-600">{{ $resource['description'] }}</p>@endif<div class="mt-4 flex flex-wrap gap-2">@if($resource['read_only'] ?? $resource['readonly'] ?? false)<span class="rounded bg-slate-200 px-2 py-1 text-xs">Read-only</span>@endif @foreach(($resource['operations'] ?? []) as $op)<span class="rounded bg-slate-100 px-2 py-1 text-xs">{{ $op }}</span>@endforeach</div></a>@endif @endforeach</div>@endif @endif</section>
@endsection
