@extends('admin.layout')
@section('content')
@php
$ops=\App\AdminHub\ResourceSchema::operations($schema); $readOnly=\App\AdminHub\ResourceSchema::readOnly($schema); $canCreate=\App\AdminHub\ResourceSchema::supports($schema,'create'); $columns=\App\AdminHub\ResourceSchema::fields($schema,'list'); $items=$itemsResponse->data['items'] ?? $itemsResponse->data['data'] ?? []; $bulk=$schema['bulk_actions'] ?? []; $label=$schema['label'] ?? \Illuminate\Support\Str::headline($resourceKey); $pagination=$itemsResponse->meta['pagination'] ?? $itemsResponse->data['pagination'] ?? [];
@endphp
<section class="rounded bg-white p-6 shadow"><div class="flex items-start justify-between gap-4"><div><p class="text-sm text-slate-500"><a href="{{ route('admin.product.resources', $productKey) }}" class="hover:underline">Resources</a> / {{ $label }}</p><h1 class="text-2xl font-bold">{{ $label }}</h1>@if($readOnly)<p class="mt-1 text-sm text-slate-500">Read-only resource</p>@elseif(! $canCreate)<p class="mt-1 text-sm text-slate-500">Create is not available for this resource.</p>@endif</div>@if($canCreate)<a class="rounded bg-blue-600 px-4 py-2 text-white" href="{{ route('admin.product.resources.create', [$productKey,$resourceKey]) }}">+ Create {{ \Illuminate\Support\Str::singular($label) }}</a>@endif</div>
@if(! $schemaResponse->success || ! $itemsResponse->success)<div class="mt-6 rounded border border-red-200 bg-red-50 p-4 text-red-800">{{ $schemaResponse->error['message'] ?? $itemsResponse->error['message'] ?? 'The product API could not be reached or returned an error.' }}</div>@else
<form method="GET" class="mt-6 flex flex-wrap gap-3">@if(($schema['searchable'] ?? $schema['searchable_fields'] ?? []))<input name="search" value="{{ request('search') }}" placeholder="Search {{ $label }}" class="rounded border p-2">@endif @foreach(($schema['filters'] ?? []) as $filter)@php($fk=$filter['key'] ?? $filter['name'] ?? null) @if($fk)<input name="filters[{{ $fk }}]" value="{{ data_get(request('filters',[]), $fk) }}" placeholder="{{ $filter['label'] ?? \Illuminate\Support\Str::headline($fk) }}" class="rounded border p-2">@endif @endforeach @if(($schema['searchable'] ?? $schema['filters'] ?? false))<button class="rounded bg-slate-700 px-4 py-2 text-white">Filter</button>@endif</form>
<form method="POST" action="{{ route('admin.product.resources.bulk', [$productKey,$resourceKey]) }}">@csrf @if($bulk)<div class="mt-4 flex gap-2"><select name="action" class="rounded border p-2">@foreach($bulk as $action)<option value="{{ $action['key'] ?? $action }}">{{ $action['label'] ?? \Illuminate\Support\Str::headline($action) }}</option>@endforeach</select><button class="rounded bg-slate-700 px-3 py-2 text-white" onclick="return confirm('Run this bulk action on selected rows?')">Apply</button></div>@endif
<div class="mt-4 overflow-auto rounded border"><table class="min-w-full divide-y"><thead class="bg-slate-50"><tr>@if($bulk)<th class="p-3"><input type="checkbox" aria-label="Select all" onclick="document.querySelectorAll('.bulk-id').forEach(c=>c.checked=this.checked)"></th>@endif @foreach($columns as $col)<th class="p-3 text-left text-sm font-semibold">@if($col['sortable'] ?? false)<a href="{{ request()->fullUrlWithQuery(['sort' => request('sort') === ($col['key'] ?? '') ? '-'.($col['key'] ?? '') : ($col['key'] ?? '')]) }}">{{ $col['label'] }}</a>@else{{ $col['label'] }}@endif</th>@endforeach<th class="p-3 text-right">Actions</th></tr></thead><tbody class="divide-y">@forelse($items as $item)@php($id=\App\AdminHub\ResourceSchema::itemId($item))<tr>@if($bulk)<td class="p-3"><input class="bulk-id" type="checkbox" name="ids[]" value="{{ $id }}"></td>@endif @foreach($columns as $col)<td class="p-3 text-sm">@include('admin.components.field',['value'=>\App\AdminHub\ResourceSchema::value($item,$col),'field'=>$col,'table'=>true])</td>@endforeach<td class="p-3 text-right text-sm"><div class="flex justify-end gap-2">@if(in_array('view',$ops,true) || in_array('read',$ops,true))<a class="text-blue-700" href="{{ route('admin.product.resources.show', [$productKey,$resourceKey,$id]) }}">View</a>@endif @if(\App\AdminHub\ResourceSchema::supports($schema,'update'))<a class="text-blue-700" href="{{ route('admin.product.resources.edit', [$productKey,$resourceKey,$id]) }}">Edit</a>@endif @if(\App\AdminHub\ResourceSchema::supports($schema,'delete'))<form method="POST" action="{{ route('admin.product.resources.destroy', [$productKey,$resourceKey,$id]) }}">@csrf @method('DELETE')<button class="text-red-700" onclick="return confirm('{{ ($schema['danger_level'] ?? '') === 'high' ? 'High-risk action. Are you sure you want to delete this record? This action may not be reversible.' : 'Are you sure you want to delete this record? This action may not be reversible.' }}')">{{ ($schema['soft_deletes'] ?? $schema['archives'] ?? false) ? 'Archive' : 'Delete' }}</button></form>@endif @if(\App\AdminHub\ResourceSchema::supports($schema,'restore') && \App\AdminHub\ResourceSchema::isDeleted($item))<form method="POST" action="{{ route('admin.product.resources.restore', [$productKey,$resourceKey,$id]) }}">@csrf<button class="text-green-700">Restore</button></form>@endif</div></td></tr>@empty<tr><td colspan="{{ count($columns)+($bulk?2:1) }}" class="p-8 text-center text-slate-500">No records found.@if($canCreate)<br><a class="mt-3 inline-block rounded bg-blue-600 px-4 py-2 text-white" href="{{ route('admin.product.resources.create', [$productKey,$resourceKey]) }}">Create your first {{ \Illuminate\Support\Str::singular($label) }}</a>@endif</td></tr>@endforelse</tbody></table></div></form>
@if($pagination)<div class="mt-4 flex gap-2 text-sm">@if($pagination['prev_page'] ?? null)<a class="rounded border px-3 py-2" href="{{ request()->fullUrlWithQuery(['page'=>$pagination['prev_page']]) }}">Previous</a>@endif @if($pagination['next_page'] ?? null)<a class="rounded border px-3 py-2" href="{{ request()->fullUrlWithQuery(['page'=>$pagination['next_page']]) }}">Next</a>@endif</div>@endif
@endif</section>
@endsection
