@extends('admin.layout')
@section('content')
@php($ops=\App\AdminHub\ResourceSchema::operations($schema)) @php($columns=\App\AdminHub\ResourceSchema::fields($schema,'list')) @php($items=$itemsResponse->data['items'] ?? $itemsResponse->data['data'] ?? []) @php($bulk=$schema['bulk_actions'] ?? [])
<section class="rounded bg-white p-6 shadow"><div class="flex items-center justify-between"><div><p class="text-sm text-slate-500"><a href="{{ route('admin.product.resources', $productKey) }}" class="hover:underline">Resources</a> / {{ $schema['label'] ?? $resourceKey }}</p><h1 class="text-2xl font-bold">{{ $schema['label'] ?? \Illuminate\Support\Str::headline($resourceKey) }}</h1></div>@if(in_array('create',$ops,true))<a class="rounded bg-blue-600 px-4 py-2 text-white" href="{{ route('admin.product.resources.create', [$productKey,$resourceKey]) }}">Create</a>@endif</div>
@if(! $schemaResponse->success || ! $itemsResponse->success)<div class="mt-6 rounded border border-red-200 bg-red-50 p-4 text-red-800">{{ $schemaResponse->error['message'] ?? $itemsResponse->error['message'] ?? 'Unable to load resource.' }}</div>@else
<form method="GET" class="mt-6 flex flex-wrap gap-3">@if(!empty($schema['searchable'] ?? $schema['searchable_fields'] ?? []))<input name="search" value="{{ request('search') }}" placeholder="Search" class="rounded border p-2">@endif @foreach(($schema['filters'] ?? []) as $filter)@php($filter=is_array($filter)?$filter:['key'=>$filter])<input name="filter[{{ $filter['key'] }}]" value="{{ data_get(request('filter',[]), $filter['key']) }}" placeholder="{{ $filter['label'] ?? $filter['key'] }}" class="rounded border p-2">@endforeach <button class="rounded bg-slate-900 px-4 py-2 text-white">Apply</button></form>
<form method="POST" action="{{ route('admin.product.resources.bulk', [$productKey,$resourceKey]) }}">@csrf @if($bulk)<div class="mt-4 flex gap-2"><select name="action" class="rounded border p-2">@foreach($bulk as $action)<option value="{{ $action['key'] ?? $action }}">{{ $action['label'] ?? $action }}</option>@endforeach</select><button class="rounded bg-slate-700 px-3 py-2 text-white" onclick="return confirm('Run this bulk action on selected rows?')">Run bulk action</button></div>@endif
<div class="mt-4 overflow-auto rounded border"><table class="min-w-full divide-y"><thead class="bg-slate-50"><tr>@if($bulk)<th class="p-3"><input type="checkbox" onclick="document.querySelectorAll('.bulk-id').forEach(c=>c.checked=this.checked)"></th>@endif @foreach($columns as $col)<th class="p-3 text-left text-sm font-semibold">@if($col['sortable'] ?? false)<a href="{{ request()->fullUrlWithQuery(['sort' => request('sort') === ($col['key'] ?? '') ? '-'.($col['key'] ?? '') : ($col['key'] ?? '')]) }}">{{ $col['label'] }}</a>@else{{ $col['label'] }}@endif</th>@endforeach<th class="p-3 text-right">Actions</th></tr></thead><tbody class="divide-y">@forelse($items as $item)@php($id=\App\AdminHub\ResourceSchema::itemId($item))<tr>@if($bulk)<td class="p-3"><input class="bulk-id" type="checkbox" name="ids[]" value="{{ $id }}"></td>@endif @foreach($columns as $col)<td class="p-3 text-sm">@include('admin.components.field',['value'=>\App\AdminHub\ResourceSchema::value($item,$col),'field'=>$col,'table'=>true])</td>@endforeach<td class="p-3 text-right text-sm"><div class="flex justify-end gap-2">@if(in_array('view',$ops,true) || in_array('read',$ops,true))<a class="text-blue-700" href="{{ route('admin.product.resources.show', [$productKey,$resourceKey,$id]) }}">View</a>@endif @if(in_array('update',$ops,true))<a class="text-blue-700" href="{{ route('admin.product.resources.edit', [$productKey,$resourceKey,$id]) }}">Edit</a>@endif @if(in_array('delete',$ops,true))<form method="POST" action="{{ route('admin.product.resources.destroy', [$productKey,$resourceKey,$id]) }}">@csrf @method('DELETE')<button class="text-red-700" onclick="return confirm('Delete this resource? This may be destructive.')">{{ $schema['delete_label'] ?? 'Delete' }}</button></form>@endif @if(in_array('restore',$ops,true))<form method="POST" action="{{ route('admin.product.resources.restore', [$productKey,$resourceKey,$id]) }}">@csrf<button class="text-green-700">Restore</button></form>@endif</div></td></tr>@empty<tr><td colspan="{{ count($columns)+2 }}" class="p-8 text-center text-slate-500">No items found.</td></tr>@endforelse</tbody></table></div></form>
@php($pagination=$itemsResponse->meta['pagination'] ?? $itemsResponse->data['pagination'] ?? []) @if($pagination)<div class="mt-4 flex gap-2 text-sm"><span>Page {{ $pagination['current_page'] ?? request('page',1) }}</span>@if($pagination['prev_page'] ?? null)<a class="text-blue-700" href="{{ request()->fullUrlWithQuery(['page'=>$pagination['prev_page']]) }}">Previous</a>@endif @if($pagination['next_page'] ?? null)<a class="text-blue-700" href="{{ request()->fullUrlWithQuery(['page'=>$pagination['next_page']]) }}">Next</a>@endif</div>@endif @endif</section>
@endsection
